## Working With Statistical Functions With Numpy Module

### Importing Necessary Modules

In [2]:
import numpy as np

### 1. np.mean(np.array, axis, dtype, ...) Function
'''
The np.mean() function provides the mean/average for the specified numpy array passed as an
input in the mean() function. It provides the mean value for the flattend array ignoring the 
shape of the array and flattend it down to a long 1-D array if no axis is specified.
'''

In [5]:
average_monthly_sales_values = list([[34.32, 23.32, 53.35, 25.08, 65.324], [38.43, 75.64, 55.35, 45.01, 35.324],
                        [76.32, 12.42, 75.32, 64.75, 53.535]])
sales_value = np.array(average_monthly_sales_values)
sales_value

array([[34.32 , 23.32 , 53.35 , 25.08 , 65.324],
       [38.43 , 75.64 , 55.35 , 45.01 , 35.324],
       [76.32 , 12.42 , 75.32 , 64.75 , 53.535]])

In [14]:
np.mean(sales_value) # this will returns the mean of the flattend array

48.89953333333332

In [11]:
np.mean(sales_value[:, 0]) # get the mean of the 1st column

49.69

In [12]:
np.mean(sales_value, axis=0) # get the mean values for all the columns

array([49.69      , 37.12666667, 61.34      , 44.94666667, 51.39433333])

In [13]:
np.mean(sales_value, axis=1) # get the mean values for all the rows

array([40.2788, 49.9508, 56.469 ])

### 2. np.min(), np.amin(), np.max(), np.amax(), np.minimum() Function

#### 2.1 np.min() Function
'''
Numpy Function np.min() finds the lowest value of an array along a given axis. If no axis is specified
(default is axis=None) then the function will work on the flattend array.
<br>
Numpy Function np.amin() is specially designed for array based operation which performs the similar 
functionality of finding the minimum value of an given array.
'''

In [22]:
sales_value

array([[34.32 , 23.32 , 53.35 , 25.08 , 65.324],
       [38.43 , 75.64 , 55.35 , 45.01 , 35.324],
       [76.32 , 12.42 , 75.32 , 64.75 , 53.535]])

In [23]:
np.min(sales_value) # gets the minimum value/item from the flattend array

12.42

In [24]:
np.min(sales_value[:, 2]) # gets the minimum value/item from the 2nd column

53.35

In [27]:
np.amin(sales_value) # gets the minimum value/item from the flattend array

12.42

In [28]:
np.amin(sales_value[:, 2]) # gets the minimum value/item from the 2nd column

53.35

#### 2.2 np.max(), np.amax() Function
'''
Numpy Function np.max() finds the maximum value of an array along a given axis. If no axis is specified
(default is axis=None) then the function will work on the flattend array.
<br>
Numpy Function np.amax() is specially designed for array based operation which performs the similar 
functionality of finding the maximum value of an given array.
'''

In [19]:
sales_value

array([[34.32 , 23.32 , 53.35 , 25.08 , 65.324],
       [38.43 , 75.64 , 55.35 , 45.01 , 35.324],
       [76.32 , 12.42 , 75.32 , 64.75 , 53.535]])

In [25]:
np.max(sales_value) # gets the maximum value/item from the flattend array

76.32

In [29]:
np.max(sales_value[:, 2]) # gets the maximum value/item from the 2nd column

75.32

In [30]:
np.amax(sales_value) # gets the maximum value/item from the flattend column

76.32

In [31]:
np.amax(sales_value[:, 2]) # gets the maximum value/item from the 2nd column

75.32

#### 2.3 np.minimum() Function
'''
Numpy Function np.minimum() requires two input arrays and generates an array which holds the 
elementwise minimum values from the given 2 input arrays. It compares the values at the same position
in each of the arrays before taking the lowest one.
'''

In [32]:
np.minimum(sales_value[0], sales_value[2]) # gets the minimum array from the 2 inputted array 

array([34.32 , 12.42 , 53.35 , 25.08 , 53.535])

#### 2.4 np.maximum() Function
'''
Numpy Function np.maximum() requires two input arrays and generates an array which holds the 
elementwise maximum values from the given 2 input arrays. It compares the values at the same position
in each of the arrays before taking the highest one.
'''

In [33]:
np.maximum(sales_value[0], sales_value[2]) # gets the maximum array from the 2 inputted array

array([76.32 , 23.32 , 75.32 , 64.75 , 65.324])